version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/housetainer/production # 인스턴스에서 파일이 저장될 위치
    overwrite: yes
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
