name: PR check

on:
  pull_request:
    branches: [ main ]

jobs:
  pr_check:
    runs-on: ubuntu-latest
    services:
      db-master:
        image: bitnami/mysql:8.0.28
        ports:
          - 3856:3306
        env:
          MYSQL_DATABASE: "housetainer"
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "Admin123"
          MYSQL_ROOT_PASSWORD: "Admin123"
          MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Unzip sql files
        env:
          ZIP_PASSWORD: ${{ secrets.SQL_ZIP_PASSWORD }}
        run: |
          cd database/migration
          7z x sql.7z -p"$ZIP_PASSWORD"
          ls
      - run: pip install requests
      - name: Check lint
        run: |
          ./gradlew lintKotlin detektAll --parallel
      - uses: pooi/detekt-comment@main
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          xml-detekt-report-path: build/reports/detekt/detekt.xml
          html-detekt-report-path: build/reports/detekt/detekt.html
      - name: Test
        run: |
          ./gradlew check -x lintKotlin -x detektAll --parallel -Phousetainer.flyway.locations=filesystem:$GITHUB_WORKSPACE/database/migration
      - name: archive test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: housetainer-*/build/reports/
      - uses: pooi/coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          xml-test-report-path: housetainer-application/build/reports/kover/report.xml,housetainer-adapter-web/build/reports/kover/report.xml,housetainer-adapter-persistence/build/reports/kover/report.xml,housetainer-web/build/reports/kover/report.xml
