name: PR check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Check lint
        run: |
          ./gradlew lintKotlin detektAll --parallel
      - uses: pooi/detekt-comment@main
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          xml-detekt-report-path: build/reports/detekt/detekt.xml
          html-detekt-report-path: build/reports/detekt/detekt.html
      - name: Test
        run: |
          ./gradlew check -x housetainer-adapter-persistence:check --parallel
            - uses: pooi/coverage-comment@main
        if: steps.check-main-code-changed.outputs.changed == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          xml-test-report-path: housetainer-web/build/reports/kover/report.xml,housetainer-application/build/reports/kover/report.xml,housetainer-adapter-web/build/reports/kover/report.xml
