name: PR check

on:
  pull_request:
    branches: [ main ]

jobs:
  pr_check:
    runs-on: ubuntu-latest
    services:
      db-master:
        image: mysql:8.0.28
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - 3856:3306
        environment:
          MYSQL_DATABASE: "housetainer"
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "Admin123"
          MYSQL_ROOT_PASSWORD: "Admin123"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Check lint
        run: |
          ./gradlew lintKotlin detektAll --parallel
      #      - uses: pooi/detekt-comment@main
      #        if: always()
      #        with:
      #          github-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
      #          xml-detekt-report-path: build/reports/detekt/detekt.xml
      #          html-detekt-report-path: build/reports/detekt/detekt.html
      - name: Test
        run: |
          ./gradlew check -x housetainer-adapter-persistence:check --parallel
#      - uses: pooi/coverage-comment@main
#        with:
#          github-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
#          xml-test-report-path: housetainer-web/build/reports/kover/report.xml,housetainer-application/build/reports/kover/report.xml,housetainer-adapter-web/build/reports/kover/report.xml
