name: Deploy to prod

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        id: new_version
        with:
          create_annotated_tag: true
          default_bump: patch
          dry_run: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          tag_prefix: ''
      - name: Build
        run: |
          ./gradlew clean build -x test --parallel -Prelease.version=${{ steps.new_version.outputs.new_tag }}
      - name: Check
        run: |
          ls housetainer-web/build/libs
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.new_version.outputs.new_tag }}
          name: Release ${{ steps.new_version.outputs.new_tag }}
          body: ${{ steps.new_version.outputs.changelog }}
          generateReleaseNotes: true
